// import Blog from "../../images/projects/Blog.png";
//import SmartBrain from './images/projects/SmartBrain.png';
import NASA from "../../images/projects/NASA.png";
import Boutique from "../../images/projects/Boutique.png";
import YODA from "../../images/projects/YODA.png";
import LemonLime from "../../images/projects/LemonLime.png";

export const projectListMERN = [
  {
    id: 1,
    title: "Lemon - Lime",
    github: "https://github.com/roseandlily33/lemon-lime",
    deployed: "https://lemon-lime.onrender.com",
    status: true,
    description:
      "A full-featured recipe management platform built with the MERN stack and MongoDB. Users can create accounts, share, edit, and delete recipes, favorite and search for recipes, and discover new dishes. Integrated image optimization and secure authentication for a seamless experience.",
    keyFeatures: [
      "User authentication and authorization with Auth0",
      "Advanced recipe search and filtering",
      "Image upload and optimization with Cloudinary and Sharp",
      "Favorites and trending recipes section",
    ],
    role: "Sole developer: designed, built, and deployed the entire application.",
    challenges: [
      "Image upload and optimization for performance - used cloudinary",
      "Responsive design for mobile and desktop",
      "Authentication and authorization with Auth0",
      "Database schema design for recipes and user profiles",
    ],
    img: LemonLime,
    type: "MERN",
    technologies: [
      "bcrypt",
      "cors",
      "cookie-parser",
      "dotenv",
      "express",
      "helmet",
      "mongodb",
      "mongoose",
      "morgan",
      "sharp",
      "tinify",
      "Auth0",
      "cloudinary",
      "tanstack query",
      "react",
      "react-router-dom",
      "styled-components",
      "uuid",
    ],
    alt: "Lemon Lime Application",
  },
  {
    id: 2,
    title: "YODA Safety Services - Client Project",
    github: "",
    deployed: "https://www.yodasafetyservices.com/",
    status: true,
    description:
      "A custom-built training and certification platform for YODA Safety Services. Enables users to create accounts, enroll in online safety courses, purchase training, and download certificates. Built for scalability and security, with a focus on user experience.",
    keyFeatures: [
      "Course enrollment and progress tracking",
      "Secure online payments and certificate downloads",
      "Automated email notifications and reminders",
      "Company Management",
      "Subcontractor Management",
      "Responsive design for mobile and desktop",
      "Admin dashboard for course and user management",
    ],
    role: "Lead developer: collaborated with client to define requirements, built and deployed the platform.",
    challenges: [
      "integrated secure payment processing",
      "automated certificate generation",
      "implemented user authentication and authorization, with different types of users",
      "working with iframes, pdfs, images and packages that support those",
    ],

    img: YODA,
    type: "MERN",
    technologies: [
      "bcrypt",
      "cors",
      "dotenv",
      "express",
      "helmet",
      "mongodb",
      "mongoose",
      "morgan",
      "jsonwebtoken",
      "multer",
      "nodemailer",
      "nodemailer-express-handlebars",
      "uuid",
      "styled-components",
      "react",
      "react-router-dom",
    ],
    alt: "YODA Application",
  },
  {
    id: 3,
    title: "Rose & Lily Boutique",
    github: "https://github.com/roseandlily33/sunshine_boutique",
    deployed: "https://superb-croquembouche-bbcbcb.netlify.app/",
    status: true,
    description:
      "An e-commerce platform for a boutique shop, featuring product browsing, shopping cart, and secure checkout. Built with React, Redux, and Firebase for real-time updates and Stripe for payments.",
    keyFeatures: [
      "Real-time product inventory with Firebase",
      "Shopping cart and secure Stripe checkout",
      "Responsive design for mobile and desktop",
    ],
    role: "Full-stack developer: handled all aspects from UI to backend integration.",
    challenges: [
      "Implemented responsive design for a seamless shopping experience across devices",
      "Integrated Firebase for real-time product updates and user authentication",
      "Managed state with Redux for efficient data handling and UI updates",
    ],
    futureDevelopment: [
      "Admin panel for product management",
      "User reviews and ratings",
    ],
    img: Boutique,
    type: "MERN",
    technologies: [
      "React",
      "Redux",
      "React-Router",
      "Styled-components",
      "Firebase",
    ],
    alt: "Rose and Lily Boutique Application",
  },
  {
    id: 4,
    title: "NASA - To The Stars",
    github: "https://github.com/roseandlily33/space-doodle",
    deployed: "https://space-doodle-nasa.onrender.com",
    status: true,
    description:
      "A space exploration dashboard using live NASA data. Users can view spaceship names, launch statuses, and mission outcomes. Built with Node, GraphQL, and React for a dynamic, interactive experience.",
    keyFeatures: [
      "Live data integration from NASA APIs",
      "Interactive mission status dashboard",
      "Modern, responsive UI",
    ],
    role: "Sole developer: designed and implemented both frontend and backend.",
    challenges: [
      "Handled inconsistent API data and optimized for fast loading.",
    ],
    img: NASA,
    type: "MERN",
    technologies: ["React", "styled-components", "Node", "express", "Mongo-DB"],
    alt: "NASA Application",
  },
  // {
  //   id: 6,
  //   title: "Shortcake Blog",
  //   github: "https://github.com/roseandlily33/cuddly-happiness",
  //   deployed: "",
  //   status: true,
  //   description:
  //     "A full stack blogging platform with user authentication, post creation/editing, and comment functionality. Built with Handlebars.js, Express, Sequelize, and custom CSS for a clean, user-friendly experience.",
  //   keyFeatures: [
  //     "User authentication and session management",
  //     "Rich text post editor",
  //     "Commenting system",
  //     "Custom CSS for unique branding",
  //   ],
  //   role: "Full-stack developer: built all features and designed the UI.",
  //   challenges:
  //     "Implemented secure authentication and optimized database queries.",
  //   img: Blog,
  //   type: "Full Stack",
  //   alt: "Shortcake Blog Application",
  // },
];
