import {
  SiRedux,
  SiGraphql,
  SiExpress,
  SiStyledcomponents,
  SiMongodb,
  SiMysql,
  SiGatsby,
  SiTestinglibrary,
  SiJavascript,
} from "react-icons/si";
import { MdAlternateEmail } from "react-icons/md";
import { RiNextjsFill } from "react-icons/ri";
import {
  FaReact,
  FaUniversalAccess,
  FaNodeJs,
  FaRegStar,
  FaAws,
  FaHtml5,
  FaCss3Alt,
  FaPaypal,
  FaRegFileExcel,
} from "react-icons/fa";

export const skills = {
  Frontend: [
    { name: "HTML", icon: <FaHtml5 />, rating: 3 },
    { name: "CSS", icon: <FaCss3Alt />, rating: 3, top: true },
    {
      name: "CSS Libraries: Bootstrap, Styled Components, Pure.css",
      icon: <SiStyledcomponents />,
      rating: 3,
    },
    { name: "Responsive Design", icon: <FaRegStar />, rating: 3 },
    { name: "JavaScript", icon: <SiJavascript />, rating: 3, top: true },
    { name: "APIs", icon: <FaRegStar />, rating: 3 },
    { name: "React", icon: <FaReact />, rating: 3, top: true },
    { name: "Next.js", icon: <RiNextjsFill />, rating: 3, top: true },
    { name: "Redux & Tanstack Query", icon: <SiRedux />, rating: 2 },
    { name: "JWTs", icon: <FaRegStar />, rating: 2 },
    { name: "Paypal", icon: <FaPaypal />, rating: 2 },
    { name: "Gatsby", icon: <SiGatsby />, rating: 3 },
    {
      name: "Visuals: Image Compression, PDFs",
      icon: <FaRegStar />,
      rating: 2,
    },
  ],
  Backend: [
    { name: "Node.js", icon: <FaNodeJs />, rating: 3, top: true },
    { name: "Express.js", icon: <SiExpress />, rating: 3 },
    { name: "MySQL", icon: <SiMysql />, rating: 2 },
    { name: "MongoDB & Mongoose", icon: <SiMongodb />, rating: 3, top: true },
    { name: "AWS Amazon", icon: <FaAws />, rating: 2 },
    { name: "GraphQL", icon: <SiGraphql />, rating: 1 },
    { name: "Multer", icon: <FaNodeJs />, rating: 2 },
    { name: "Bcrypt", icon: <FaNodeJs />, rating: 2 },
    { name: "xlsx files", icon: <FaRegFileExcel />, rating: 1 },
    { name: "Winston", icon: <FaNodeJs />, rating: 1 },
    { name: "Database Design", icon: <FaRegStar />, rating: 2 },
  ],
  Other: [
    { name: "UX/UI Design", icon: <FaRegStar />, rating: 3, top: true },
    { name: "SEO", icon: <FaRegStar />, rating: 2 },
    { name: "Cyber Security", icon: <FaRegStar />, rating: 2 },
    { name: "CORS", icon: <FaRegStar />, rating: 1 },
    { name: "Testing", icon: <SiTestinglibrary />, rating: 1 },
    { name: "Performance", icon: <FaRegStar />, rating: 1 },
    { name: "Sessions & JWT", icon: <FaRegStar />, rating: 1 },
    { name: "CI/CD", icon: <FaRegStar />, rating: 1 },
    { name: "PWAs", icon: <FaRegStar />, rating: 1 },
    {
      name: "Emails: MJML, Handlebars, nodemailer, react-email",
      icon: <MdAlternateEmail />,
      rating: 3,
    },
  ],
  SoftSkills: [
    { name: "Organization", icon: <FaRegStar />, rating: 3 },
    { name: "Communication", icon: <FaRegStar />, rating: 2 },
    { name: "Problem Solving", icon: <FaRegStar />, rating: 3 },
    { name: "Leadership Roles", icon: <FaRegStar />, rating: 2 },
    { name: "Accessibility", icon: <FaUniversalAccess />, rating: 2 },
  ],
};
